### ISSUE TITLE
The website for this repo points to wrong URL

### ISSUE THREAD

**Issue by trawick** [aldryn/aldryn-locations#11]
The description and website for the project are displayed near the top of Github's page for this project; they show "integrate Google Maps into Aldryn and django CMS sites via Google's API http://www.aldryn.com/en/marketplace/aldryn-google-analytics/"

![image](https://cloud.githubusercontent.com/assets/1207350/11566488/a5fd71e6-99b0-11e5-8f8d-a2364bd235f3.png)

The URL is incorrect.

**Comment by vxsx** [comment]
thanks a lot for the report, I changed the url to a correct one
